Menu:
  Home: /
  Archives: /archives/
  About: /about/
  # Category: /category_archive
  # Tag: /tag_archive
  Github: https://github.com/vevlins/
  RSS: /atom.xml
  Search: true
  
Site:
  Motto: Ponyo loves Sōsuke! 

Intro:
  Avastar: img/avastar.jpeg
  Name: 张强
  Brief: 2019届重庆大学本科生,前端学习者
  SNS: 
    Weibo:  
    StackOverflow: 
    Github: https://github.com/Vevlins
    Pinterest: 
    Quora: 

CopyRight: 
  Author: Sōsuke
  License: CC BY-NC-SA 3.0 CN

Tip:
  Alipay: /img/qrcode.jpeg
  Wechat: /img/qrcode.jpeg

Comment:
  Id: 8d83609a651e972e308d
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774de
  Repo: Vevlins.github.io
  Owner: Vevlins